# Configuration file for database small elements

# You have to provide the tags used here. Tags are identified by their name (it
# will be converted to upper case, it should be just one word). You can provide
# a color id (positive integer starting at 0).
#
# For each tag use the following example:
#  - name: example-tag
#    color_id: 0
tags:
  - name: PV
    color_hue: 162
  - name: AMV
    color_hue: 140
  - name: LIVE
    color_hue: 100
  - name: LONG
    color_hue: 280
  - name: COURT
    color_hue: 255
  - name: COVER
    color_hue: 65
  - name: REMIX
    color_hue: 20
  - name: INST
    color_hue: 215
  - name: SPOIL
    color_hue: 360
  - name: NSFW
    color_hue: 315

# You have to provide the types of works used here. Work types are identified by
# their query name (hyphenated name, with no special characters, used as key
# word for querying). You can provide a work type display name and a icon name.
# (the name is choosen among the [FontAwesome](http://fontawesome.io/icons/)
# font glyphes).
#
# For each line, use the following example:
#  - query_name: example-work-type
#    name: Example Work Type
#    icon_name: smile-o
worktypes:
  - query_name: anime
    name: Anime
    name_plural: Animes
    icon_name: television
  - query_name: live-action
    name: Live action
    name_plural: Live actions
    icon_name: film
  - query_name: game
    name: Game
    name_plural: Games
    icon_name: gamepad
  - query_name: cartoon
    name: Cartoon
    name_plural: Cartoons
    icon_name: globe
