version: '3'
services:
  dakara:
    container_name: dakara
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:22222"
    volumes:
      - ./db:/db
      - /path/to/kara/base:/karabase
